name: Deploy to EC2
# masterにpushされた時にjobを実行する
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
    # 保存したシークレットたちを環境変数に設定
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      run:
        # 秘密鍵にファイル名secret_keyをつける
        echo "${SECRET_KEY}" > secret_key
        chmod 600 secret_key
        # ssh接続　＞　デプロイするディレクトリに行く　＞　デプロイ
        ssh -oStrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} -i secret_key "git pull"
